name: car_locator_2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.7
  uuid: ^2.0.4
  sqflite: ^1.1.7+3
  intl: ^0.16.0
  curved_navigation_bar: ^0.3.1 #latest version
  quick_actions: ^0.3.3+1
  provider: ^3.0.0+1
  progress_dialog: ^1.2.0
  google_maps_flutter: ^0.5.21+11
  cloud_firestore: ^0.12.10+2
  firebase_auth: ^0.14.0+5
  #flutter_map: any
  #flutter_maps: ^0.1.0
  geoflutterfire: ^2.0.3+2
  firebase_core: ^0.4.0+9
  location: ^2.3.5
  google_maps_webservice: ^0.0.14
  random_color: ^1.0.3
  http: ^0.12.0+2
  geolocator: ^5.1.5
  #db

  path_provider: ^0.4.1
  font_awesome_flutter: ^8.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  geocoder: ^0.1.2
  flutter_google_places: ^0.2.3
  share: ^0.6.3+1
  get_it: ^1.0.3+2
  shared_preferences: ^0.5.4+5
  flutter_spinkit: "^4.0.0"
  rxdart:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

module:
    androidX: true 
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/mapc.jpg
    - images/image2.jpg
  #plugin:
   # androidPackage: io.flutter.plugins.quickactions
    #iosPrefix: FLT
    #pluginClass: QuickActionsPlugin
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
